steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mygkecloud/my-image', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-service', '--image', 'gcr.io/mygkecloud/my-image', '--platform', 'managed']

serviceAccount: my-service-account@mygkecloud.iam.gserviceaccount.com
logsBucket: gs://triggerbucket1
